language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.pip --use-mirrors"
  - "ssh-keygen -t rsa -N \"\" -f ~/.ssh/id_rsa"
  - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
  - "ls -l ~/.ssh/"
script:
  - "fab on_:travis test"
notifications:
  email: false