language: python
python:
  - "2.7"
install:
  - "ssh-keygen -t rsa -N \"\" -f ~/.ssh/my_id_rsa"
  - "echo \"Host 127.0.0.1\" >> ~/.ssh/config"
  - "echo \"HostName 127.0.0.1\" >> ~/.ssh/config"
  - "echo \"PreferredAuthentications publickey\" >> ~/.ssh/config"
  - "echo \"IdentityFile ~/.ssh/my_id_rsa\" >> ~/.ssh/config"
  - "cat ~/.ssh/my_id_rsa.pub >> ~/.ssh/authorized_keys"
  - "ls -l ~/.ssh/"
  - "pip install -r requirements.pip --use-mirrors"
script:
  - "fab on_:travis test"
notifications:
  email: false